server:
  port: 9180

logging:
  level:
    root: INFO
    io.github.resilience4j: DEBUG

# https://resilience4j.readme.io/docs/getting-started-3

# 服务熔断
resilience4j.circuitbreaker:
  configs:
    default:
      ringBufferSizeInClosedState: 5 # 熔断器关闭时的缓冲区大小
      ringBufferSizeInHalfOpenState: 2 # 熔断器半开时的缓冲区大小
      waitDurationInOpenState: 10000 # 熔断器从打开到半开需要的时间
      failureRateThreshold: 60 # 以百分比配置故障率阈值
      eventConsumerBufferSize: 10 # 事件缓冲区大小
      registerHealthIndicator: true # 健康监测
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true # 是否自动从打开到半开，不需要触发
      #recordFailurePredicate:    com.example.resilience4j.exceptions.RecordFailurePredicate # 谓词设置异常是否为失败
      recordExceptions: # 记录的异常
        - com.github.jsjchai.resilience4j.exception.DBException
        - java.util.concurrent.TimeoutException
      ignoreExceptions: # 忽略的异常
        - com.github.jsjchai.resilience4j.exception.DBException
        - com.github.jsjchai.resilience4j.exception.BusinessException
  instances:
    order:
      baseConfig: default

# 并发控制
resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 2
  instances:
    order:
      maxConcurrentCalls: 2
      maxWaitDuration: 1000ms




